#pragma once
#define NOMINMAX

#include <memory>
#include <map>
#include <string>
#include <vector>
#include <algorithm>
#include <fstream>
#include <sstream>
#include <cassert>
#include <functional>
#include <cmath>
#include <DirectXMath.h>
#include <chrono>
#include <list>
#include <mutex>
#include <thread>
#include <iostream>
#include <crtdbg.h>
#include <unordered_map>
#include <math.h>
#include <unordered_set>
#include <tuple>
#include <atomic>
#include <DxLib.h>
#include <cstdlib>
#include <EffekseerForDXLib.h>
